apiVersion: v1
kind: ServiceAccount
metadata:
  name: bakeoff-workload
  namespace: bakeoff
  annotations:
    iam.gke.io/workload-identity: bakeoff-workload@exalted-kit-496514-s1.iam.gserviceaccount.com
