apiVersion: apps/v1
kind: Deployment
metadata:
  name: tax-service
  namespace: bakeoff
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: tax-service
  template:
    metadata:
      labels:
        app: tax-service
    spec:
      nodeSelector:
        cloud.google.com/gke-spot: "true"
      tolerations:
        - effect: NoSchedule
          key: cloud.google.com/gke-spot
          operator: Equal
          value: "true"
      containers:
        - name: tax-service
          image: us-west1-docker.pkg.dev/exalted-kit-496514-s1/portfolio/bakeoff-tax-service:4c2ecab7
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "25m"
              memory: "32Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: tax-service
  namespace: bakeoff
spec:
  selector:
    app: tax-service
  ports:
    - port: 8080
      targetPort: 8080
